### ISSUE TITLE
MIT licence ?

### ISSUE THREAD

**Issue by frelle** [tschoffelen/csv-hero#3]
Hi,
Super repo, there is any licence (MIT, public) to reuse it ?
thanks

**Comment by tschoffelen** [comment]
I'll add a licence file today.

Out of curiosity, how are you planning to reuse it?

**Comment by frelle** [comment]
thanks.
Well, I have just discovered your repo, I'm playing with it, and maybe I'll integrate it into my script. I don't yet, but maybe. And without knowing the license, I prefer not ;)
